# Source of text to match patterns with.
#
# Possible values: primary or clipboard
# "primary" sees whatever text you select in an application
# "clipboard" sees what you copy to it with Ctrl-C
#
# See also http://www.freedesktop.org/wiki/Specifications/clipboards-spec
# for an explanation of the terms.
text_source: clipboard

# If true, ctoolu activates whenever the watched space changes.
# If false, an explicit activation is necessary, via ctoolu-activate or DBus.
auto_activate: true